name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Install west and set up ZMK
        run: |
          pip install west
          git clone https://github.com/zmkfirmware/zmk.git zmk
          cd zmk
          west init -l app
          west update
          west zephyr-export

      - name: Build firmware (left)
        run: |
          cd zmk
          west build -s app -b akdk_bt1 -d ../build/left \
            -- -DSHIELD=kod_01_left \
               -DZMK_CONFIG=${{ github.workspace }}/config \
               -DZMK_EXTRA_MODULES=${{ github.workspace }} \
               -DCONFIG_ZMK_STUDIO=y \
               -DSNIPPET=studio-rpc-usb-uart

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/left/zephyr/zmk.uf2
